spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrm?&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      fitters: stat,wall

      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      aop-patterns: com.ma2.admin.*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

